#!/usr/bin/env bash

mkdir ~/.ssh
mv ~/clouddrive/azuredeploy.json ~
mv ~/clouddrive/id_rsa ~/clouddrive/id_rsa.pub .ssh/
chmod 600 ~/.ssh/id_rsa
chmod 644 ~/.ssh/id_rsa.pub

echo "Keys moved to ~/.ssh"